
# For more details, please see referenes/gitpod-yml
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev 

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode

    - esbenp.prettier-vscode

    - dbaeumer.vscode-eslint

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
